# Generated by Django 2.2.7 on 2019-11-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('video_url', models.CharField(max_length=1000)),
                ('dekripsi', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_judul', models.CharField(max_length=225)),
                ('home_image_url', models.CharField(max_length=1000)),
                ('home_video_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
