# Generated by Django 2.2.7 on 2019-11-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='dekripsi',
            new_name='deskripsi',
        ),
    ]
