# Generated by Django 2.2.7 on 2019-11-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20191116_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_url',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
