# Generated by Django 2.2.7 on 2019-11-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_auto_20191120_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image2_url',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='image3_url',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
