# Generated by Django 2.2.7 on 2020-01-29 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0008_auto_20200129_1158'),
        ('artwork', '0008_auto_20200129_1223'),
    ]

    operations = [
    ]
